### PR TITLE
varint: Fix VarInt serialization and deserialization

### LINKED ISSUE #4: VarInt encoding is not applied to primitives
During the test write I have discovered that the VarInt is not used for primitives even if configured.

### PR DESCRIPTION
**Pull request by almusil**
VarInt was skipped for all primitives. Align it with main bincode
code base. Rename simple tests as fixint.

Fixes #4

### CODE REVIEW

**Comment by almusil** [comment]
This should be probably merged before #3 and after rebase I will add all the basic scenarios to cover also varint.

**Comment by VictorKoenders** [comment]
I think the old `tests/simple.rs` should be restored without the fixint encoding.
Maybe even renamed to `tests/simple_default_options.rs`.
The new test can stay in the `tests/simple_fixint.rs` file.
This way we test both encodings.

**Comment by almusil** [comment]
> I think the old `tests/simple.rs` should be restored without the fixint encoding.
> Maybe even renamed to `tests/simple_default_options.rs`.
> The new test can stay in the `tests/simple_fixint.rs` file.
> This way we test both encodings.

I was thinking about covering both of them with same subset just with difference in the option. Does it make sense?

**Comment by VictorKoenders** [comment]
I'm okay with either, but the current test only covers `.with_fixint_encoding()`, not the default settings

**Comment by almusil** [comment]
Ok updated to keep the defaults and I'll adjust the tests after merge.

**Comment by VictorKoenders** [comment]
Looks good to me!

**Pull request merged**
